<?php

function d8_angular_starter_theme($existing, $type, $theme, $path) {
    return array(
        'd8_angular_starter' => array(
            'variables' => array(
                'base_href'=>NULL,
                'content' => NULL
            )
        ),
    );
}

function template_preprocess_d8_angular_starter(&$vars){
    $vars['#attached']['library'][] = 'd8_angular_starter/d8_angular_starter';
    $vars['#attached']['drupalSettings']['d8_angular_starter'] = array(
        'module_path'=>drupal_get_path('module', 'd8_angular_starter')
    );
}